"""Single-GPU PPO actor with rollout inference and per-table KV caches."""

from __future__ import annotations

from dataclasses import dataclass
from collections import defaultdict
import asyncio
from contextlib import contextmanager
import time
from typing import Any

import numpy as np
import torch
from torch.distributions import Categorical

try:
    import ray
except ImportError:
    ray = None

from .learner import PPOLearner
from .profiling import StageProfiler
from .trajectory import Transition


@dataclass
class _CacheEntry:
    generation: int
    history_length: int
    key_values: tuple[tuple[torch.Tensor, torch.Tensor], ...]


if ray is not None:
    @ray.remote(num_gpus=1, max_concurrency=128)
    class RolloutInferenceActor:
        """The only process that owns the PPO model, optimizer and CUDA context.

        Each RPC already contains all active decisions of one environment
        worker.  Calls are serialized by this actor, which naturally batches
        GPU work within that request and avoids competing CUDA contexts.
        """

        def __init__(self, config: dict[str, Any]) -> None:
            if not torch.cuda.is_available():
                raise RuntimeError("central rollout inference requires CUDA")
            self.config = config
            self.device = torch.device("cuda")
            self.dtype = torch.bfloat16 if str(config.get("inference_dtype", "bf16")) == "bf16" else torch.float16
            hyperparameters = {key: value for key, value in config.items() if key not in {"model_size", "device"}}
            self.learner = PPOLearner(str(config["model_size"]), "cuda", **hyperparameters)
            if config.get("resume"):
                self.learner.load(config["resume"])
            self.model = self.learner.model.eval()
            self.cached_forward: Any | None = None
            if bool(config.get("inference_compile", True)):
                self.cached_forward = torch.compile(self.model.forward_cached, mode="reduce-overhead")
            self.cache: dict[tuple[str, int, int], _CacheEntry] = {}
            self.profiler = StageProfiler(enabled=bool(config.get("profile_enabled", True)))
            self.profile_cuda_sync = bool(config.get("profile_cuda_sync", True))
            self.cache_hits = 0
            self.cache_misses = 0
            self.cache_resets = 0
            self.cache_full_fallbacks = 0
            self.full_fallback_valid_tokens = 0
            self.full_fallback_padded_tokens = 0
            self._profile_checkpoint = self.profiler.checkpoint()
            self._profile_cache_checkpoint = (0, 0, 0, 0)
            self._profile_fallback_token_checkpoint = (0, 0)
            self._pending: list[tuple[dict[str, Any], asyncio.Future[dict[str, Any]]]] = []
            self._drain_task: asyncio.Task[None] | None = None

        def _sync_cuda(self) -> None:
            if self.profile_cuda_sync:
                torch.cuda.synchronize(self.device)

        @contextmanager
        def _gpu_stage(self, name: str):
            """Measure the GPU work submitted in this stage, including its fence."""
            self._sync_cuda()
            with self.profiler.stage(name):
                try:
                    yield
                finally:
                    self._sync_cuda()

        def begin_rollout(self) -> None:
            """Start a synchronous on-policy rollout using the current model weights."""
            self.cache.clear()
            self.cache_resets += 1
            self._profile_checkpoint = self.profiler.checkpoint()
            self._profile_cache_checkpoint = (
                self.cache_hits, self.cache_misses, self.cache_resets, self.cache_full_fallbacks,
            )
            self._profile_fallback_token_checkpoint = (
                self.full_fallback_valid_tokens, self.full_fallback_padded_tokens,
            )

        def iteration(self) -> int:
            return int(self.learner.iteration)

        def update(self, transitions: list[Transition]) -> dict[str, float]:
            """Optimise the same model that served the completed rollout."""
            metrics = self.learner.update(transitions)
            self.model.eval()
            # Cached keys/values were generated by the old policy parameters.
            self.cache.clear()
            self.cache_resets += 1
            return metrics

        def save(self, path: str, train_config: dict[str, Any]) -> None:
            self.learner.save(path, train_config)

        def clear_namespace(self, namespace: str) -> None:
            doomed = [key for key in self.cache if key[0] == namespace]
            for key in doomed:
                del self.cache[key]
            self.cache_resets += len(doomed)

        def profile_summary(self) -> dict[str, float]:
            """Return one iteration's actor totals without RPC fan-out double counting."""
            stats = self.profiler.delta(self._profile_checkpoint, prefix="timing")
            before = self._profile_cache_checkpoint
            token_before = self._profile_fallback_token_checkpoint
            valid_tokens = self.full_fallback_valid_tokens - token_before[0]
            padded_tokens = self.full_fallback_padded_tokens - token_before[1]
            stats.update({
                "inference/cache_hits": float(self.cache_hits - before[0]),
                "inference/cache_misses": float(self.cache_misses - before[1]),
                "inference/cache_resets": float(self.cache_resets - before[2]),
                "inference/cache_full_fallbacks": float(self.cache_full_fallbacks - before[3]),
                "inference/cache_entries": float(len(self.cache)),
                "inference/cache_tokens": float(sum(entry.history_length for entry in self.cache.values())),
                "inference/full_fallback_valid_tokens": float(valid_tokens),
                "inference/full_fallback_padded_tokens": float(padded_tokens),
                "inference/full_fallback_padding_fraction": float(
                    padded_tokens / max(valid_tokens + padded_tokens, 1)
                ),
            })
            return stats

        async def infer(
            self,
            *,
            worker_id: int,
            namespace: str,
            batch_indices: list[int],
            ids: np.ndarray,
            lengths: np.ndarray,
            legal_mask: np.ndarray,
            history_lengths: np.ndarray,
            history_generations: np.ndarray,
            greedy: bool,
        ) -> dict[str, Any]:
            loop = asyncio.get_running_loop()
            future: asyncio.Future[dict[str, Any]] = loop.create_future()
            self._pending.append(({
                "worker_id": worker_id, "namespace": namespace,
                "batch_indices": batch_indices, "ids": ids, "lengths": lengths,
                "legal_mask": legal_mask, "history_lengths": history_lengths,
                "history_generations": history_generations, "greedy": greedy,
            }, future))
            if self._drain_task is None:
                self._drain_task = asyncio.create_task(self._drain_requests())
            return await future

        async def _drain_requests(self) -> None:
            # A tiny window is sufficient for the four synchronous workers to
            # arrive at the same decision tick.  GPU work then runs outside
            # awaits while the actor owns a single CUDA context.
            await asyncio.sleep(max(0.0, float(self.config.get("inference_batch_wait_ms", 1.0))) / 1_000.0)
            while self._pending:
                pending, self._pending = self._pending, []
                try:
                    results = self._infer_many([request for request, _future in pending])
                    for (_request, future), result in zip(pending, results):
                        if not future.done():
                            future.set_result(result)
                except Exception as exc:
                    for _request, future in pending:
                        if not future.done():
                            future.set_exception(exc)
            self._drain_task = None

        def _infer_many(self, requests: list[dict[str, Any]]) -> list[dict[str, Any]]:
            started = time.perf_counter()
            responses = [{"action_ids": [0] * len(request["batch_indices"]), "logprobs": [0.0] * len(request["batch_indices"]), "values": [0.0] * len(request["batch_indices"])} for request in requests]
            # KV prefixes are ragged across tables.  Bucket equal prefix and
            # suffix lengths so every bucket is a true GPU batch without
            # requiring padded cache masks (which would disable fast SDPA).
            buckets: dict[tuple[int, int, int, bool, bool], list[tuple[int, int, tuple[str, int, int], int, Any]]] = defaultdict(list)
            for request_index, request in enumerate(requests):
                if len(request["batch_indices"]) != len(request["lengths"]) or request["ids"].shape[0] != len(request["batch_indices"]):
                    raise ValueError("decision metadata batch dimensions differ")
                for row, batch_index in enumerate(request["batch_indices"]):
                    key = (str(request["namespace"]), int(request["worker_id"]), int(batch_index))
                    history_length = int(request["history_lengths"][row])
                    generation = int(request["history_generations"][row])
                    total_length = int(request["lengths"][row])
                    entry = self.cache.get(key)
                    valid = bool(self.config.get("rollout_kv_cache", True)) and entry is not None and entry.generation == generation and entry.history_length <= history_length
                    if valid:
                        self.cache_hits += 1
                        base, past = entry.history_length, entry.key_values
                    else:
                        self.cache_misses += 1
                        base, past = 0, None
                    buckets[(base, history_length, total_length, past is not None, bool(request["greedy"]))].append((request_index, row, key, generation, past))
            max_batch = max(1, int(self.config.get("inference_max_batch_size", 512)))
            # A small Transformer is faster on one full padded GPU batch than
            # on many tiny ragged-cache kernels.  Keep cache semantics, but
            # adaptively choose the full path when one worker tick fragments
            # into too many distinct prefix lengths.
            keys_per_request: dict[int, set[tuple[int, int, int, bool, bool]]] = defaultdict(set)
            for key, rows in buckets.items():
                for request_index, _row, _cache_key, _generation, _past in rows:
                    keys_per_request[request_index].add(key)
            max_buckets = max(1, int(self.config.get("inference_kv_max_buckets", 4)))
            full_requests = {request_index for request_index, keys in keys_per_request.items() if len(keys) > max_buckets}
            for request_index in full_requests:
                request = requests[request_index]
                total_length = int(request["ids"].shape[1])
                batch_size = len(request["batch_indices"])
                valid_tokens = int(np.asarray(request["lengths"], dtype=np.int64).sum())
                self.full_fallback_valid_tokens += valid_tokens
                self.full_fallback_padded_tokens += batch_size * total_length - valid_tokens
                with self._gpu_stage("inference/full_sequence_fallback_h2d"):
                    full_ids = torch.as_tensor(np.array(request["ids"], copy=True), device=self.device, dtype=torch.long)
                    full_legal = torch.as_tensor(np.array(request["legal_mask"], copy=True), device=self.device, dtype=torch.bool)
                    full_lengths = torch.as_tensor(np.array(request["lengths"], copy=True), device=self.device, dtype=torch.long)
                    full_attention = torch.arange(total_length, device=self.device).unsqueeze(0) < full_lengths.unsqueeze(1)
                with self._gpu_stage("inference/full_sequence_fallback_model_forward"):
                    with torch.inference_mode(), torch.autocast(device_type="cuda", dtype=self.dtype):
                        output = self.model(full_ids, full_legal, full_attention, full_lengths)
                with self._gpu_stage("inference/full_sequence_fallback_sample_and_d2h"):
                    with torch.inference_mode():
                        distribution = Categorical(logits=output["policy_logits"])
                        chosen = output["policy_logits"].argmax(-1) if bool(request["greedy"]) else distribution.sample()
                        for row, (action, logprob, value) in enumerate(zip(chosen.tolist(), distribution.log_prob(chosen).tolist(), output["value"].tolist())):
                            responses[request_index]["action_ids"][row] = int(action)
                            responses[request_index]["logprobs"][row] = float(logprob)
                            responses[request_index]["values"][row] = float(value)
                self.cache_full_fallbacks += 1
            for (base, history_length, total_length, has_past, greedy), rows in buckets.items():
                rows = [item for item in rows if item[0] not in full_requests]
                if not rows:
                    continue
                for offset in range(0, len(rows), max_batch):
                    group = rows[offset:offset + max_batch]
                    with self._gpu_stage("inference/h2d"):
                        group_ids = torch.as_tensor(np.array([requests[request_index]["ids"][row, :total_length] for request_index, row, _key, _generation, _past in group], copy=True), device=self.device, dtype=torch.long)
                        group_legal = torch.as_tensor(np.array([requests[request_index]["legal_mask"][row] for request_index, row, _key, _generation, _past in group], copy=True), device=self.device, dtype=torch.bool)
                    if history_length == 0:
                        # Protocol probes may construct a decision without
                        # first replaying events. It is valid for mask
                        # validation but has no append-only prefix to cache.
                        self.cache_misses += 1
                        with self._gpu_stage("inference/uncached_fallback"):
                            with torch.inference_mode(), torch.autocast(device_type="cuda", dtype=self.dtype):
                                output = self.model(group_ids, group_legal, torch.ones((len(group), total_length), device=self.device, dtype=torch.bool), torch.full((len(group),), total_length, device=self.device, dtype=torch.long))
                        next_cache = None
                    else:
                        history = group_ids[:, base:history_length]
                        snapshot = group_ids[:, history_length:total_length]
                        past = None
                        if has_past:
                            past = tuple((torch.cat([item[4][layer][0] for item in group], dim=0), torch.cat([item[4][layer][1] for item in group], dim=0)) for layer in range(len(self.model.blocks)))
                        with self._gpu_stage("inference/cache_prefill" if past is None else "inference/cache_append"):
                            with torch.inference_mode(), torch.autocast(device_type="cuda", dtype=self.dtype):
                                runner = self.cached_forward or self.model.forward_cached
                                output, next_cache = runner(history, snapshot, group_legal, past, base)
                        if bool(self.config.get("rollout_kv_cache", True)):
                            for index, (_request_index, _row, key, generation, _past) in enumerate(group):
                                split_cache = tuple((pair[0][index:index + 1].clone(), pair[1][index:index + 1].clone()) for pair in next_cache)
                                self.cache[key] = _CacheEntry(generation, history_length, split_cache)
                    with self._gpu_stage("inference/sample_and_d2h"):
                        distribution = Categorical(logits=output["policy_logits"])
                        chosen = output["policy_logits"].argmax(-1) if greedy else distribution.sample()
                        chosen_cpu = chosen.tolist()
                        logprob_cpu = distribution.log_prob(chosen).tolist()
                        value_cpu = output["value"].tolist()
                        for index, (request_index, row, _key, _generation, _past) in enumerate(group):
                            responses[request_index]["action_ids"][row] = int(chosen_cpu[index])
                            responses[request_index]["logprobs"][row] = float(logprob_cpu[index])
                            responses[request_index]["values"][row] = float(value_cpu[index])
            self.profiler.add("inference/rpc_total", time.perf_counter() - started)
            return responses
else:
    RolloutInferenceActor = None
