"""Play one traced hanchan: a checkpoint policy against heuristic opponents.

The trace records only decisions made by the checkpoint player.  It is meant
for human inspection, so it keeps the complete legal action set alongside the
visible table and the model's private hand at every decision point.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import time
from typing import Any

# Keep the repository's CUDA_DEVICE convention when this tool is invoked
# directly, before importing torch.
if os.environ.get("CUDA_DEVICE") and not os.environ.get("CUDA_VISIBLE_DEVICES"):
    os.environ["CUDA_VISIBLE_DEVICES"] = os.environ["CUDA_DEVICE"]

import numpy as np
import torch
from torch.nn import functional as F

import riichi
from riichienv import BatchedRiichiEnv

from riichi_ppo_v1.model.bridge import BatchedStateBridge, Decision, tile_id_to_mjai
from riichi_ppo_v1.training.learner import PPOLearner
from riichi_ppo_v1.training.opponents.heuristic import HeuristicPolicy
from riichi_ppo_v1.training.rewards import DecisionAnalysisBatch, EfficiencyAnalyzer, PublicStateTracker
from riichi_ppo_v1.training.train import load_config
from riichi_ppo_v1.training.worker import active_decisions


def _action_kind(action: Any) -> str:
    value = getattr(action, "action_type", getattr(action, "type", ""))
    return str(getattr(value, "name", value)).lower()


def _action_label(action: Any, action_id: int, mjai: str) -> str:
    parsed = json.loads(mjai)
    kind = str(parsed.get("type", _action_kind(action)))
    tile = parsed.get("pai")
    suffix = f" {tile}" if tile is not None else ""
    if kind == "dahai":
        # The canonical JSON generated by the bridge includes tsumogiri.
        suffix += " (tsumogiri)" if parsed.get("tsumogiri") else " (tedashi)"
    return f"{action_id}: {kind}{suffix}  {mjai}"


def _tiles(tiles: list[int] | tuple[int, ...]) -> str:
    return " ".join(tile_id_to_mjai(tile) or "?" for tile in tiles)


def _public_table(observation: Any) -> list[str]:
    def render_meld(meld: Any) -> str:
        kind = str(getattr(getattr(meld, "meld_type", ""), "name", getattr(meld, "meld_type", ""))).lower()
        tiles = _tiles(list(getattr(meld, "tiles", ())))
        called = tile_id_to_mjai(getattr(meld, "called_tile", None)) or "-"
        source = getattr(meld, "from_who", "-")
        return f"{kind}({tiles}; called={called}; from=Seat {source})"

    rows = []
    for seat in range(4):
        discards = _tiles(list(observation.discards[seat]))
        melds = ", ".join(render_meld(meld) for meld in observation.melds[seat]) or "-"
        rows.append(
            f"Seat {seat}: river=[{discards}] melds=[{melds}]"
            + (" RIICHI" if observation.riichi_declared[seat] else "")
        )
    return rows


def _write_decision(file: Any, number: int, bridge: BatchedStateBridge, decision: Decision,
                    legal_mask: np.ndarray, chosen_id: int, log_probs: np.ndarray) -> None:
    observation = decision.observation
    wind = "ESWN"[int(observation.round_wind)]
    file.write(f"\n## Decision {number}: Seat {observation.player_id}\n\n")
    file.write(
        f"Round: {wind}{int(observation.kyoku_index) + 1}; dealer=Seat {observation.oya}; "
        f"honba={observation.honba}; riichi_sticks={observation.riichi_sticks}; "
        f"scores={list(observation.scores)}; dora=[{_tiles(list(observation.dora_indicators))}]\n\n"
    )
    file.write(f"Hand: [{_tiles(list(observation.hands[observation.player_id]))}]\n\n")
    file.write(f"Drawn tile: {tile_id_to_mjai(getattr(observation, 'drawn_tile', None)) or '-'}\n\n")
    file.write("Visible table:\n\n")
    for row in _public_table(observation):
        file.write(f"- {row}\n")
    file.write("\nLegal options (policy probability):\n\n")
    enabled = np.flatnonzero(legal_mask)
    # Multiple physical copies of a tile can be one policy action.  Decode
    # every enabled fixed action id to present the policy's actual option set.
    decoded = bridge.state_machine.decode_actions(
        [decision.batch_index] * len(enabled), [int(action_id) for action_id in enabled],
    )
    rows = []
    for action_id, raw in zip(enabled, decoded, strict=True):
        action = observation.select_action_from_mjai(raw)
        if action is None:
            raise RuntimeError(f"could not render legal policy action {action_id}: {raw}")
        rows.append((int(action_id), action, raw))
    for action_id, action, raw in rows:
        probability = float(np.exp(log_probs[action_id]))
        marker = " ← SELECTED" if int(action_id) == chosen_id else ""
        file.write(f"- {_action_label(action, int(action_id), raw)}; p={probability:.4%}{marker}\n")
    selected = next(row for row in rows if row[0] == chosen_id)
    file.write(f"\nSelected: {_action_label(selected[1], chosen_id, selected[2])}\n")


def run(checkpoint: Path, output: Path, seed: int, seat: int) -> None:
    config = load_config()
    config["resume"] = str(checkpoint)
    device = "cuda:0" if torch.cuda.is_available() else "cpu"
    hyperparameters = {key: value for key, value in config.items() if key not in {"model_size", "device"}}
    learner = PPOLearner(str(config["model_size"]), device, **hyperparameters)
    learner.load(checkpoint)
    model = learner.model.eval()
    envs = BatchedRiichiEnv(1, seed=seed, step_threads=1, game_mode=str(config["game_mode"]))
    bridge = BatchedStateBridge(riichi.MjaiKyokuStateMachineManager(1), 1)
    observations = list(envs.reset())
    bridge.sync(observations)
    public = PublicStateTracker(1)
    public.update(bridge.last_events)
    efficiency = EfficiencyAnalyzer(int(config.get("reward_cache_capacity", 131_072)))
    heuristics = (
        HeuristicPolicy(efficiency, public, defensive=False),
        HeuristicPolicy(efficiency, public, defensive=True),
        HeuristicPolicy(efficiency, public, defensive=False),
    )
    opponent_by_seat = {other: heuristics[index] for index, other in enumerate(s for s in range(4) if s != seat)}
    output.parent.mkdir(parents=True, exist_ok=True)
    started = time.perf_counter()
    decisions_logged = 0
    kyokus = 0
    with output.open("w", encoding="utf-8") as file:
        file.write("# Checkpoint decision trace\n\n")
        file.write(f"Checkpoint: `{checkpoint}`  \nSeed: `{seed}`  \nModel seat: `Seat {seat}`  \n")
        file.write("Opponents: efficiency heuristic, defensive heuristic, efficiency heuristic (in seat order excluding model).\n")
        for step in range(4000):
            actions_by_env: list[dict[int, Any]] = [{}]
            decisions = active_decisions(observations)
            analysis = DecisionAnalysisBatch.build(
                decisions, analyzer=efficiency, public=public,
            ) if decisions else None
            for decision in decisions:
                if decision.seat_id != seat:
                    actions_by_env[0][decision.seat_id] = opponent_by_seat[decision.seat_id].select_batch([decision], analysis)[0]
                    continue
                factors, numeric, lengths, legal_mask, _generation, critic, critic_lengths = bridge.prepare(
                    [decision], analysis,
                )
                with torch.inference_mode(), torch.autocast(device_type=device.split(":")[0], dtype=torch.bfloat16, enabled=learner.use_bf16):
                    result = model(
                        torch.as_tensor(factors, device=device, dtype=torch.long),
                        torch.as_tensor(numeric, device=device, dtype=torch.float32),
                        torch.as_tensor(legal_mask, device=device, dtype=torch.bool),
                        torch.as_tensor(lengths, device=device, dtype=torch.long),
                        critic_factors=torch.as_tensor(critic, device=device, dtype=torch.long),
                        critic_lengths=torch.as_tensor(critic_lengths, device=device, dtype=torch.long),
                    )
                log_probs = F.log_softmax(result["policy_logits"][0], dim=-1).cpu().numpy()
                chosen_id = int(result["policy_logits"][0].argmax().item())
                action = bridge.decode([decision], [chosen_id])[0]
                decisions_logged += 1
                _write_decision(
                    file, decisions_logged, bridge, decision, legal_mask[0], chosen_id, log_probs,
                )
                actions_by_env[0][seat] = action
            observations = list(envs.step_batch(actions_by_env))
            end_kyoku, _end_game = bridge.sync(observations)
            public.update(bridge.last_events)
            if bool(end_kyoku[0]):
                kyokus += 1
            if bool(envs.done()[0]):
                file.write(f"\n# Final result\n\nScores: {list(map(int, envs.scores()[0]))}; kyokus={kyokus}; steps={step + 1}; elapsed={time.perf_counter() - started:.2f}s\n")
                break
        else:
            raise RuntimeError("game exceeded 4000 environment steps")
    print(f"trace={output} decisions={decisions_logged} kyokus={kyokus} scores={list(map(int, envs.scores()[0]))} elapsed_s={time.perf_counter() - started:.2f}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", type=Path, default=Path("checkpoints/train_riichi_v8/best_kyoku.pt"))
    parser.add_argument("--output", type=Path, default=Path("checkpoints/train_riichi_v8/best_kyoku_hanchan_trace.md"))
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--seat", type=int, choices=range(4), default=0)
    args = parser.parse_args()
    run(args.checkpoint, args.output, args.seed, args.seat)


if __name__ == "__main__":
    main()
